version: '3'
services:
  db:
    image: postgres
    env_file: 
      - .env
  web:
    build: .
    command: python example/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
